# Generated by Django 5.1.1 on 2024-09-22 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField()),
            ],
        ),
    ]
