# Generated by Django 5.1.1 on 2024-09-22 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
